// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: crawler.proto

package pb

import (
	fmt "fmt"
	_ "github.com/Felyne/crawler/distributed/service/gomicro/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Crawler service

type CrawlerService interface {
	Process(ctx context.Context, in *Request, opts ...client.CallOption) (*ParseResult, error)
}

type crawlerService struct {
	c    client.Client
	name string
}

func NewCrawlerService(name string, c client.Client) CrawlerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb"
	}
	return &crawlerService{
		c:    c,
		name: name,
	}
}

func (c *crawlerService) Process(ctx context.Context, in *Request, opts ...client.CallOption) (*ParseResult, error) {
	req := c.c.NewRequest(c.name, "Crawler.Process", in)
	out := new(ParseResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Crawler service

type CrawlerHandler interface {
	Process(context.Context, *Request, *ParseResult) error
}

func RegisterCrawlerHandler(s server.Server, hdlr CrawlerHandler, opts ...server.HandlerOption) error {
	type crawler interface {
		Process(ctx context.Context, in *Request, out *ParseResult) error
	}
	type Crawler struct {
		crawler
	}
	h := &crawlerHandler{hdlr}
	return s.Handle(s.NewHandler(&Crawler{h}, opts...))
}

type crawlerHandler struct {
	CrawlerHandler
}

func (h *crawlerHandler) Process(ctx context.Context, in *Request, out *ParseResult) error {
	return h.CrawlerHandler.Process(ctx, in, out)
}
