// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package pb_crawler // import "github.com/Felyne/crawler/distributed/service/gomicro/worker/pb_crawler"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/Felyne/crawler/distributed/service/gomicro/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceName int32

const (
	ServiceName_CRAWLER_SERVICE ServiceName = 0
)

var ServiceName_name = map[int32]string{
	0: "CRAWLER_SERVICE",
}
var ServiceName_value = map[string]int32{
	"CRAWLER_SERVICE": 0,
}

func (x ServiceName) String() string {
	return proto.EnumName(ServiceName_name, int32(x))
}
func (ServiceName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_crawler_b7b0c97562e9f46c, []int{0}
}

type SerializedParser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Args                 []byte   `protobuf:"bytes,2,opt,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedParser) Reset()         { *m = SerializedParser{} }
func (m *SerializedParser) String() string { return proto.CompactTextString(m) }
func (*SerializedParser) ProtoMessage()    {}
func (*SerializedParser) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_b7b0c97562e9f46c, []int{0}
}
func (m *SerializedParser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedParser.Unmarshal(m, b)
}
func (m *SerializedParser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedParser.Marshal(b, m, deterministic)
}
func (dst *SerializedParser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedParser.Merge(dst, src)
}
func (m *SerializedParser) XXX_Size() int {
	return xxx_messageInfo_SerializedParser.Size(m)
}
func (m *SerializedParser) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedParser.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedParser proto.InternalMessageInfo

func (m *SerializedParser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SerializedParser) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type Request struct {
	Url                  string            `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	SerializedParser     *SerializedParser `protobuf:"bytes,2,opt,name=SerializedParser,proto3" json:"SerializedParser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_b7b0c97562e9f46c, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetSerializedParser() *SerializedParser {
	if m != nil {
		return m.SerializedParser
	}
	return nil
}

type ParseResult struct {
	Items                []*common.Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	Requests             []*Request     `protobuf:"bytes,2,rep,name=Requests,proto3" json:"Requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ParseResult) Reset()         { *m = ParseResult{} }
func (m *ParseResult) String() string { return proto.CompactTextString(m) }
func (*ParseResult) ProtoMessage()    {}
func (*ParseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_b7b0c97562e9f46c, []int{2}
}
func (m *ParseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResult.Unmarshal(m, b)
}
func (m *ParseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResult.Marshal(b, m, deterministic)
}
func (dst *ParseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResult.Merge(dst, src)
}
func (m *ParseResult) XXX_Size() int {
	return xxx_messageInfo_ParseResult.Size(m)
}
func (m *ParseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResult.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResult proto.InternalMessageInfo

func (m *ParseResult) GetItems() []*common.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ParseResult) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*SerializedParser)(nil), "pb_crawler.SerializedParser")
	proto.RegisterType((*Request)(nil), "pb_crawler.Request")
	proto.RegisterType((*ParseResult)(nil), "pb_crawler.ParseResult")
	proto.RegisterEnum("pb_crawler.ServiceName", ServiceName_name, ServiceName_value)
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_crawler_b7b0c97562e9f46c) }

var fileDescriptor_crawler_b7b0c97562e9f46c = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0xa2, 0xa2, 0x53, 0x8c, 0x64, 0x39, 0x48, 0x88, 0x07, 0xd2, 0x13, 0xf1, 0xd0, 0x4d,
	0xf0, 0xa4, 0x37, 0x44, 0xd4, 0x26, 0xc6, 0x90, 0x25, 0x6a, 0xe2, 0x85, 0xb4, 0x65, 0x82, 0x1b,
	0x5b, 0x16, 0x67, 0xb7, 0x12, 0xfd, 0x7a, 0xd3, 0x76, 0x23, 0x8d, 0x78, 0xf2, 0xd4, 0x97, 0x37,
	0xf3, 0x5e, 0xdf, 0xdb, 0x81, 0xa3, 0x98, 0xc2, 0x75, 0x82, 0xe4, 0xaf, 0x48, 0x19, 0xc5, 0x60,
	0x15, 0xcd, 0x2c, 0xd3, 0x0d, 0x16, 0xd2, 0xbc, 0x66, 0x91, 0x1f, 0xab, 0x94, 0xdf, 0x60, 0xf2,
	0xb9, 0x44, 0x6e, 0x47, 0x7c, 0x2e, 0xb5, 0x21, 0x19, 0x65, 0x06, 0xe7, 0x5c, 0x23, 0x7d, 0xc8,
	0x18, 0xf9, 0x42, 0xa5, 0x32, 0x26, 0xc5, 0x63, 0x95, 0xa6, 0x6a, 0x69, 0x3f, 0xa5, 0xad, 0x77,
	0x09, 0xad, 0x29, 0x92, 0x0c, 0x13, 0xf9, 0x85, 0xf3, 0x49, 0x48, 0x1a, 0x89, 0x31, 0xd8, 0x7d,
	0x08, 0x53, 0xec, 0x38, 0x3d, 0xa7, 0x7f, 0x28, 0x0a, 0x9c, 0x73, 0x43, 0x5a, 0xe8, 0xce, 0x4e,
	0xcf, 0xe9, 0x37, 0x45, 0x81, 0x3d, 0x84, 0x86, 0xc0, 0xf7, 0x0c, 0xb5, 0x61, 0x2d, 0xa8, 0x3f,
	0x52, 0x62, 0x15, 0x39, 0x64, 0x77, 0xdb, 0xc6, 0x85, 0xd8, 0x1d, 0x9c, 0xfa, 0x9b, 0x2a, 0xfe,
	0xef, 0x1d, 0xb1, 0xa5, 0xf2, 0x22, 0x70, 0x0b, 0x24, 0x50, 0x67, 0x89, 0x61, 0x1e, 0xec, 0x05,
	0x06, 0x53, 0xdd, 0x71, 0x7a, 0xf5, 0xbe, 0x3b, 0x68, 0xfa, 0xb6, 0x4f, 0x4e, 0x8a, 0x72, 0xc4,
	0x38, 0x1c, 0xd8, 0x64, 0x79, 0xe2, 0x7c, 0xad, 0x5d, 0xfd, 0xa9, 0x9d, 0x89, 0x9f, 0xa5, 0x33,
	0x0f, 0xdc, 0x69, 0xf9, 0x5a, 0x45, 0xdb, 0x36, 0x1c, 0x8f, 0xc4, 0xf0, 0xf9, 0x7e, 0x2c, 0x66,
	0xd3, 0xb1, 0x78, 0x0a, 0x46, 0xe3, 0x56, 0x6d, 0x70, 0x0d, 0x8d, 0x51, 0x69, 0xc0, 0x2e, 0xa0,
	0x31, 0x21, 0x15, 0xa3, 0xd6, 0xec, 0x2f, 0xe3, 0xee, 0x49, 0x95, 0xac, 0x84, 0xf7, 0x6a, 0x57,
	0xc1, 0xcb, 0xed, 0xff, 0xae, 0xb7, 0x56, 0xf4, 0x86, 0xc4, 0x37, 0xc6, 0xd1, 0x7e, 0x71, 0xc2,
	0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x87, 0xef, 0x1d, 0x2a, 0x02, 0x00, 0x00,
}
